# vim: ts=2:sts=2:sw=2:expandtab:smarttab:

pipeline:
  build:
    image: andrexus/golang-dep
    commands:
      - export GOPATH=$(pwd)
      - cd src/ergo
      - dep ensure -vendor-only
      - go build

  publish-docker:
    image: plugins/docker
    repo: ontrif/ergo
    tag:
      - latest
      - ${DRONE_TAG}
    when:
      event: tag
    secrets: [ docker_username, docker_password ]
